### ISSUE TITLE
versionning

### ISSUE THREAD

**Issue by Fabiyo-90** [nativescript-vue/nativescript-vue#252] opened 2018-06-16 11:11 UTC
I wanna know wich version for nativescript-vue, tns-core-modules and tns-android for production ?
I wanna begin a project for enterprise !

my Error is 
An uncaught Exception occured on "main" thread.
com.tns.NativeScriptException:
Calling js method run failde

TypeError: Cannot read property '__ob__' of undefined
File: "file:///data/data/cd.fabiyo.eshida/files/app/app.js, line: 1, column 110155"

And I don't know why but I have impression that the project is not ready for production because too much bug

I created three pages including A, B and C.
my application opens with page A then using the router I go to page B with $ router.push; arrived at page B I go to page C using the router with $ router.push. Once on page C, when I press the return key with my android then I have a bug without knowing why.
I created my project with nativescript-view / view-cli including nativescript-view 1.3.1, tns-core-modules 3.4.1 and tns-android 4.1.2

I like it a lot and I get the impression that the NativeScript team does not care a bit about it when they talk about it in the official site!

**Comment by Fabiyo-90** [comment] 2018-06-19 12:15
I think it will focus on a single version of nativescript-view that will be compatible with a version of tns-core-modules and tns-android so there will be no ease in the bug tracking, and if there has a new version of tns-core-module and tns-android then it will require a new version nativescript-view that will be revised in order to be compatible with the new versions.
This is because I am totally lost, before the router worked fine and now there is a bug and I am stuck in my project that I have to present this Saturday!


System.err: com.tns.NativeScriptException:
System.err: Calling js method run failed
System.err:
System.err: TypeError: Cannot read property '__ob__' of undefined
System.err: File: "file:///data/data/cd.fabiyo.eshida/files/app/app.js, line: 1, column: 110155
System.err:
System.err: StackTrace:
System.err:     Frame: function:'e.$destroy', file:'file:///data/data/cd.fabiyo.eshida/files/app/app.js', line: 1, column: 110156
System.err:     Frame: function:'', file:'file:///data/data/cd.fabiyo.eshida/files/app/app.js', line: 1, column: 131721
System.err:     Frame: function:'', file:'file:///data/data/cd.fabiyo.eshida/files/app/app.js', line: 1, column: 27579
System.err:     Frame: function:'ViewBase._tearDownUI', file:'file:///data/data/cd.fabiyo.eshida/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 489, column: 14
System.err:     Frame: function:'ViewBase._removeViewCore', file:'file:///data/data/cd.fabiyo.eshida/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 382, column: 18
System.err:     Frame: function:'ViewBase._removeView', file:'file:///data/data/cd.fabiyo.eshida/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 373, column: 14
System.err:     Frame: function:'FrameBase._removeEntry', file:'file:///data/data/cd.fabiyo.eshida/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 202, column: 19
System.err:     Frame: function:'Frame._removeEntry', file:'file:///data/data/cd.fabiyo.eshida/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 199, column: 39
System.err:     Frame: function:'FrameBase._updateBackstack', file:'file:///data/data/cd.fabiyo.eshida/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 260, column: 18
System.err:     Frame: function:'Frame.setCurrent', file:'file:///data/data/cd.fabiyo.eshida/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 108, column: 18
System.err:     Frame: function:'', file:'file:///data/data/cd.fabiyo.eshida/files/app/tns_modules/tns-core-modules/ui/frame/fragment.transitions.js', line: 563, column: 53
System.err:     Frame: function:'invoke', file:'file:///data/data/cd.fabiyo.eshida/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 19, column: 48
System.err:     Frame: function:'run', file:'file:///data/data/cd.fabiyo.eshida/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 23, column: 13
System.err:
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:970)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:954)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:946)
System.err:     at com.tns.gen.java.lang.Runnable.run(Runnable.java:15)
System.err:     at android.os.Handler.handleCallback(Handler.java:789)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
System.err:     at android.os.Looper.loop(Looper.java:164)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6541)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
ActivityManager: Process cd.fabiyo.eshida (pid 1703) has died: fore TOP
ActivityManager: setHasOverlayUi called on unknown pid: 1703
Terminer le programme de commandes (O/N) ? O

**Comment by jlooper** [comment] 2018-06-25 14:20
Closed as dupe of #269

**Closed by jlooper** 2018-06-25 14:20 UTC
Labels: priority:low
