### ISSUE TITLE
** EXPORT FAILED **  Command xcodebuild failed with exit code 70

### ISSUE THREAD

**Issue by keithgulbroIT** [nativescript-vue/nativescript-vue#415] opened 2019-01-11 05:02 UTC
### Version
2.0.2

### Reproduction link
[https://github.com/keithgulbroIT/Nativescript-Vue-Sample-Application](https://github.com/keithgulbroIT/Nativescript-Vue-Sample-Application)
### Platform and OS info
Max OS Majave 10.14, Nativescript version: 5.1, iOS is the platform target for release

### Steps to reproduce
$ npm install -g @vue/cli @vue/cli-init
$ vue init nativescript-vue/vue-cli-template <project-name>
$ cd <project-name>
$ npm install
(Open nativescriptsample.xcworkspace) and select profile/team)
$ tns build ios --release (Successful)
$ tns publish ios (Errors)

### What is expected?
Successfully published application to itunes connect

Please note that I have a valid itunes connect account with valid certificates.

### What is actually happening?
Binaries:
/Applications/nativescriptsample.app/app/tns_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework
/Applications/nativescriptsample.app/app/tns_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/Current/Electron Framework

This can happen if your build process copies frameworks by following symlinks. }
error: exportArchive: /Users/kgulbro/Desktop/Sites/nativescript-sample/platforms/ios/build/archive/nativescriptsample.xcarchive/Products contains invalid products.

Error Domain=IDEFoundationErrorDomain Code=1 "/Users/kgulbro/Desktop/Sites/nativescript-sample/platforms/ios/build/archive/nativescriptsample.xcarchive/Products contains invalid products." UserInfo={NSLocalizedDescription=/Users/kgulbro/Desktop/Sites/nativescript-sample/platforms/ios/build/archive/nativescriptsample.xcarchive/Products contains invalid products., NSLocalizedRecoverySuggestion=Multiple binaries share the same codesign path:
/Applications/nativescriptsample.app/app/tns_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/Current

Binaries:
/Applications/nativescriptsample.app/app/tns_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework
/Applications/nativescriptsample.app/app/tns_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/Current/Electron Framework

This can happen if your build process copies frameworks by following symlinks. }

** EXPORT FAILED **

Command xcodebuild failed with exit code 70

---
Package.json looks as follows: 

{
  "name": "nativescript-sample",
  "version": "1.0.0",
  "description": "A native application built with NativeScript-Vue",
  "author": "Keith Gulbro <keith.gulbro@irishtitan.com>",
  "license": "MIT",
  "nativescript": {
    "id": "org.nativescript.application",
    "tns-ios": {
      "version": "5.1.0"
    },
    "tns-android": {
      "version": "5.1.0"
    }
  },
  "dependencies": {
    "@vue/devtools": "5.0.0-beta.3",
    "nativescript-socket.io": "^0.9.0",
    "nativescript-toast": "^1.4.6",
    "nativescript-vue": "^2.0.0",
    "nativescript-vue-devtools": "^1.0.0",
    "tns-core-modules": "^5.1.1"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "babel-loader": "^8.0.2",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "clean-webpack-plugin": "^0.1.19",
    "copy-webpack-plugin": "^4.5.2",
    "css-loader": "^1.0.0",
    "lazy": "1.0.11",
    "nativescript-dev-webpack": "next",
    "nativescript-vue-template-compiler": "^2.0.0",
    "nativescript-worker-loader": "~0.9.0",
    "node-sass": "^4.9.2",
    "sass-loader": "^7.1.0",
    "terser-webpack-plugin": "^1.1.0",
    "vue-loader": "^15.2.6",
    "webpack": "^4.16.4",
    "webpack-bundle-analyzer": "~2.13.1",
    "webpack-cli": "^3.1.0"
  }
}

Please note that running tns build ios --release is successful and running tns run ios --bundle is also successful.

Please also note, I have an application built in nativescript-vue experiencing the same issue and is pending deployment to both app stores once this bug is addressed. Thank you in advance for any assistance you can give!

**Comment by keithgulbroIT** [comment] 2019-01-11 22:38
Update:
If I remove vue-dev-tools the error is removed but I still encounter an issue in which I can run tns build ios --release successfully but opening `.xcworkspace` file inside iOS -> platforms and attempting to run the application throws the following error:

```
2019-01-11 16:34:51.751911-0600 samplenativescriptvue[48517:12969561] JavaScript error:
2019-01-11 16:34:51.766037-0600 samplenativescriptvue[48517:12969561] [native code]: JS ERROR Error: Could not find module './components/App'. Computed path '/Users/kgulbro/Library/Developer/CoreSimulator/Devices/B6A87A95-87F8-4D65-87FE-CFCD0C5853AC/data/Containers/Bundle/Application/10E11674-5BE6-49EF-8004-EFE6E179CD19/samplenativescriptvue.app/app/components/App'.

[native code]: JS ERROR Error: Could not find module './components/App'. Computed path '/Users/kgulbro/Library/Developer/CoreSimulator/Devices/B6A87A95-87F8-4D65-87FE-CFCD0C5853AC/data/Containers/Bundle/Application/10E11674-5BE6-49EF-8004-EFE6E179CD19/samplenativescriptvue.app/app/components/App'.
2019-01-11 16:34:51.767430-0600 samplenativescriptvue[48517:12969561] *** JavaScript call stack:
(

)
2019-01-11 16:34:51.767640-0600 samplenativescriptvue[48517:12969561] *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Error: Could not find module './components/App'. Computed path '/Users/kgulbro/Library/Developer/CoreSimulator/Devices/B6A87A95-87F8-4D65-87FE-CFCD0C5853AC/data/Containers/Bundle/Application/10E11674-5BE6-49EF-8004-EFE6E179CD19/samplenativescriptvue.app/app/components/App'.
 at 
1   resolveSync@[native code]
2   @[native code]
3   promiseReactionJob@[native code]
', reason: '(null)'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001067c71bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x00000001055d7735 objc_exception_throw + 48
	2   NativeScript                        0x00000001034cf5ef _ZN12NativeScript30reportFatalErrorBeforeShutdownEPN3JSC9ExecStateEPNS0_9ExceptionEbb + 1119
	3   NativeScript                        0x000000010350ba5f -[TNSRuntime executeModule:referredBy:] + 799
	4   samplenativescriptvue               0x0000000102cd2ab3 main + 179
	5   libdyld.dylib                       0x0000000106d97575 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by vratojr** [comment] 2019-01-12 17:10
Same problem here, cannot publish! :( Did you go any further?

**Comment by rigor789** [comment] 2019-02-18 23:06
Yes, seems like a duplicate of #395. See my detailed answer: https://github.com/nativescript-vue/nativescript-vue/issues/395#issuecomment-444444139

**Closed by rigor789** 2019-02-18 23:06 UTC
Labels: priority:normal
