### ISSUE TITLE
Image component not working when wrapped in custom Component "Cannot convert object to Landroid/graphics/Bitmap; at index 0

### ISSUE THREAD

**Issue by hgouveia** [nativescript-vue/nativescript-vue#302] opened 2018-08-08 15:47 UTC
Nativescript version: 4.2.0
Nativescript-vue : 1.3.1 

Hello,
Im having exactly the same issue as https://github.com/NativeScript/NativeScript/issues/2895

The issue is in this line on Profile.vue

` <Image row="0" class="avatar" :src="user.avatar" stretch="aspectFill" />`

but works if i do 

`<Image row="0" class="avatar" src="http://via.placeholder.com/256x256" stretch="aspectFill" />`

*Home.vue*
```html
<template>
  <Page class="page">
    <ActionBar class="action-bar" title="Home Page"/>
    <StackLayout>
      <ListView for="user in users">
        <v-template>
          <Profile v-bind:user="user" />
        </v-template>
      </ListView>
    </StackLayout>
  </Page>
</template>
<script>
import Profile from '../../components/Profile';
import { knownFolders } from 'tns-core-modules/file-system';
export default {
    components: { Profile },
    name: "home",
    created() {
        this.getUsers();
    },
    data() {
        return {
            users: {}
        };
    },
    methods: {
        getUsers() {
            knownFolders
                .currentApp()
                .getFile('data/users.json')
                .readText()
                .then(content => this.users = JSON.parse(content))
                .catch(err => console.error(err));
        }
    }
};
</script>
```

*Profile.vue*
```html
<template>
<GridLayout class="profile" rows="75" columns="75, *" >
    <Image row="0" col="0" class="avatar" :src="user.avatar" stretch="aspectFill" />
    <Label row="0" col="1" :text="user.screen_name" />
</GridLayout>
</template>
<script>
export default { props: ["user"] };
</script>
```

*users.json*
```json
[
    {
        "screen_name" : "My User",
        "avatar" : "http:\/\/via.placeholder.com\/256x256"
    },
    {
        "screen_name" : "User My",
        "avatar" : "http:\/\/via.placeholder.com\/256x256"
    }
]
```

*Error*
```
JS: 'NativeScript-Vue has "Vue.config.silent" set to true, to see output logs set it to false.'
System.err: com.tns.NativeScriptException:
System.err: Calling js method getView failed
System.err: Error: Cannot convert object to Landroid/graphics/Bitmap; at index 0
System.err: File: "file:///data/data/org.app.test/files/app/tns_modules/tns-core-modules/ui/image/image.js, line: 143, column: 23
System.err: StackTrace:
System.err:     Frame: function:'Image.(anonymous function)', file:'file:///data/data/org.app.test/files/app/tns_modules/tns-core-modules/ui/image/image.js', line: 143, column: 24
System.err:     Frame: function:'Property.set', file:'file:///data/data/org.app.test/files/app/tns_modules/tns-core-modules/ui/core/properties/properties.js', line: 116, column: 44
System.err:     Frame: function:'ImageBase._createImageSourceFromSrc', file:'file:///data/data/org.app.test/files/app/tns_modules/tns-core-modules/ui/image/image-common.js', line: 107, column: 30
System.err:     Frame: function:'Image._createImageSourceFromSrc', file:'file:///data/data/org.app.test/files/app/tns_modules/tns-core-modules/ui/image/image.js', line: 101, column: 56
System.err:     Frame: function:'Image.(anonymous function)', file:'file:///data/data/org.app.test/files/app/tns_modules/tns-core-modules/ui/image/image.js', line: 154, column: 14
System.err:     Frame: function:'applyAllNativeSetters', file:'file:///data/data/org.app.test/files/app/tns_modules/tns-core-modules/ui/core/properties/properties.js', line: 961, column: 28
System.err:     Frame: function:'initNativeView', file:'file:///data/data/org.app.test/files/app/tns_modules/tns-core-modules/ui/core/properties/properties.js', line:
905, column: 9
System.err:     Frame: function:'ViewBase.onResumeNativeUpdates', file:'file:///data/data/org.app.test/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 555, column: 22
System.err:     Frame: function:'ViewBase._resumeNativeUpdates', file:'file:///data/data/org.app.test/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 223, column: 18
System.err:     Frame: function:'ViewBase.onLoaded', file:'file:///data/data/org.app.test/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 200, column: 14
System.err:     Frame: function:'View.onLoaded', file:'file:///data/data/org.app.test/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
System.err:     Frame: function:'', file:'file:///data/data/org.app.test/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 206, column: 19
System.err:     Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.app.test/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err:     Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.app.test/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
System.err:     Frame: function:'ViewBase._loadEachChild', file:'file:///data/data/org.app.test/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 205, column: 14
System.err:     Frame: function:'ViewBase.onLoaded', file:'file:///data/data/org.app.test/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 201, column: 14
System.err:     Frame: function:'View.onLoaded', file:'file:///data/data/org.app.test/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
System.err:     Frame: function:'ViewBase._addViewCore', file:'file:///data/data/org.app.test/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 360, column: 18
System.err:     Frame: function:'ViewBase._addView', file:'file:///data/data/org.app.test/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 346, column: 14
System.err:     Frame: function:'ListViewAdapter.getView', file:'file:///data/data/org.app.test/files/app/tns_modules/tns-core-modules/ui/list-view/list-view.js', line: 257, column: 36
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:983)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:967)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err:     at com.tns.gen.android.widget.BaseAdapter_view_185_32_ListViewAdapter.getView(BaseAdapter_view_185_32_ListViewAdapter.java:52)
System.err:     at android.widget.AbsListView.obtainView(AbsListView.java:2929)
System.err:     at android.widget.ListView.measureHeightOfChildren(ListView.java:1305)
System.err:     at android.widget.ListView.onMeasure(ListView.java:1212)
System.err:     at android.view.View.measure(View.java:20151)
System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     at org.nativescript.widgets.StackLayout.onMeasure(StackLayout.java:83)
System.err:     at android.view.View.measure(View.java:20151)
System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     at org.nativescript.widgets.MeasureHelper.measureChildFixedColumnsAndRows(GridLayout.java:1055)
System.err:     at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:865)
System.err:     at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:279)
System.err:     at android.view.View.measure(View.java:20151)
System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     at org.nativescript.widgets.ContentLayout.onMeasure(ContentLayout.java:32)
System.err:     at android.view.View.measure(View.java:20151)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
System.err:     at android.view.View.measure(View.java:20151)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
System.err:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
System.err:     at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
System.err:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
System.err:     at android.view.View.measure(View.java:20151)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
System.err:     at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:3158)
System.err:     at android.view.View.measure(View.java:20151)
System.err:     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2594)
System.err:     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1549)
System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1841)
System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7397)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:695)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:631)
System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
System.err:     at android.os.Handler.handleCallback(Handler.java:739)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:158)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7225)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
ActivityManager: Process org.app.test (pid 4600)(adj 0) has died(90,487)
```

**Comment by rigor789** [comment] 2018-08-08 16:05
Duplicate of https://github.com/nativescript-vue/nativescript-vue/issues/231

This issue has been fixed in 2.0 see linked issue for more details...

**Closed by rigor789** 2018-08-08 16:05 UTC
Labels: priority:low
