### ISSUE TITLE
Geolocation working on Nativescript playground but not locally

### ISSUE THREAD

**Issue by jgirgis85** [nativescript-vue/nativescript-vue#152] opened 2018-03-22 17:44 UTC
When I add the nativescript library for geolocation using

`npm install --save nativescript-geolocation`

and add the require file in my home vue file like so: 

`var Geolocation = require("nativescript-geolocation");`

`and then run: npm run watch:android`

I get the below error so what am I missing:

`System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException:
System.err:
System.err: Error calling module function
System.err:
System.err: Error: com.tns.NativeScriptException: Failed to find module: "nativescript-geolocation\geolocation.common", relative to: app/tns_modules/
System.err:     com.tns.Module.resolvePathHelper(Module.java:146)
System.err:     com.tns.Module.resolvePath(Module.java:55)
System.err:     com.tns.Runtime.runModule(Native Method)
System.err:     com.tns.Runtime.runModule(Runtime.java:530)
System.err:     com.tns.Runtime.run(Runtime.java:522)
System.err:     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
System.err:     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
System.err:     android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
System.err:     android.app.ActivityThread.-wrap2(ActivityThread.java)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
System.err:     android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     android.os.Looper.loop(Looper.java:154)
System.err:     android.app.ActivityThread.main(ActivityThread.java:6119)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
System.err: File: "<unknown>, line: 1, column: 265
System.err:
System.err: StackTrace:
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 199786
System.err:     Frame: function:'e', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 198344
System.err:     Frame: function:'e', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 177298
System.err:     Frame: function:'e', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
System.err:     Frame: function:'Object.defineProperty.value', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 176923
System.err:     Frame: function:'e', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
System.err:     Frame: function:'Object.defineProperty.value', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 149889
System.err:     Frame: function:'e', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 147651
System.err:     Frame: function:'e', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 511
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 521
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:
System.err:
System.err: Error: com.tns.NativeScriptException: Failed to find module: "nativescript-geolocation\geolocation.common", relative to: app/tns_modules/
System.err:     com.tns.Module.resolvePathHelper(Module.java:146)
System.err:     com.tns.Module.resolvePath(Module.java:55)
System.err:     com.tns.Runtime.runModule(Native Method)
System.err:     com.tns.Runtime.runModule(Runtime.java:530)
System.err:     com.tns.Runtime.run(Runtime.java:522)
System.err:     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
System.err:     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
System.err:     android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
System.err:     android.app.ActivityThread.-wrap2(ActivityThread.java)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
System.err:     android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     android.os.Looper.loop(Looper.java:154)
System.err:     android.app.ActivityThread.main(ActivityThread.java:6119)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
System.err: File: "<unknown>, line: 1, column: 265
System.err:
System.err: StackTrace:
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 199786
System.err:     Frame: function:'e', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 198344
System.err:     Frame: function:'e', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 177298
System.err:     Frame: function:'e', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
System.err:     Frame: function:'Object.defineProperty.value', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 176923
System.err:     Frame: function:'e', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
System.err:     Frame: function:'Object.defineProperty.value', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 149889
System.err:     Frame: function:'e', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 147651
System.err:     Frame: function:'e', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 511
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 521
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5406)
System.err:     at android.app.ActivityThread.-wrap2(ActivityThread.java)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     at android.os.Looper.loop(Looper.java:154)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
System.err: Caused by: com.tns.NativeScriptException:
System.err:
System.err: Error calling module function
System.err:
System.err: Error: com.tns.NativeScriptException: Failed to find module: "nativescript-geolocation\geolocation.common", relative to: app/tns_modules/
System.err:     com.tns.Module.resolvePathHelper(Module.java:146)
System.err:     com.tns.Module.resolvePath(Module.java:55)
System.err:     com.tns.Runtime.runModule(Native Method)
System.err:     com.tns.Runtime.runModule(Runtime.java:530)
System.err:     com.tns.Runtime.run(Runtime.java:522)
System.err:     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
System.err:     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
System.err:     android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
System.err:     android.app.ActivityThread.-wrap2(ActivityThread.java)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
System.err:     android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     android.os.Looper.loop(Looper.java:154)
System.err:     android.app.ActivityThread.main(ActivityThread.java:6119)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
System.err: File: "<unknown>, line: 1, column: 265
System.err:
System.err: StackTrace:
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 199786
System.err:     Frame: function:'e', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 198344
System.err:     Frame: function:'e', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 177298
System.err:     Frame: function:'e', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
System.err:     Frame: function:'Object.defineProperty.value', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 176923
System.err:     Frame: function:'e', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
System.err:     Frame: function:'Object.defineProperty.value', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 149889
System.err:     Frame: function:'e', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 147651
System.err:     Frame: function:'e', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 511
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 521
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:
System.err:
System.err: Error: com.tns.NativeScriptException: Failed to find module: "nativescript-geolocation\geolocation.common", relative to: app/tns_modules/
System.err:     com.tns.Module.resolvePathHelper(Module.java:146)
System.err:     com.tns.Module.resolvePath(Module.java:55)
System.err:     com.tns.Runtime.runModule(Native Method)
System.err:     com.tns.Runtime.runModule(Runtime.java:530)
System.err:     com.tns.Runtime.run(Runtime.java:522)
System.err:     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
System.err:     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
System.err:     android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
System.err:     android.app.ActivityThread.-wrap2(ActivityThread.java)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
System.err:     android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     android.os.Looper.loop(Looper.java:154)
System.err:     android.app.ActivityThread.main(ActivityThread.java:6119)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
System.err: File: "<unknown>, line: 1, column: 265
System.err:
System.err: StackTrace:
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 199786
System.err:     Frame: function:'e', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 198344
System.err:     Frame: function:'e', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 177298
System.err:     Frame: function:'e', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
System.err:     Frame: function:'Object.defineProperty.value', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 176923
System.err:     Frame: function:'e', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
System.err:     Frame: function:'Object.defineProperty.value', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 149889
System.err:     Frame: function:'e', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 147651
System.err:     Frame: function:'e', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 511
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 521
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:
System.err:     at com.tns.Runtime.runModule(Native Method)
System.err:     at com.tns.Runtime.runModule(Runtime.java:530)
System.err:     at com.tns.Runtime.run(Runtime.java:522)
System.err:     at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
System.err:     ... 8 more
ActivityManager: Process org.nativescript.application (pid 1272) has died
ActivityManager: cleanUpApplicationRecord -- 1272`

**Comment by rigor789** [comment] 2018-03-22 18:57
Are you running this on windows? if so, this is a path issue in `nativescript-vue-externals`, and it is tracked here: https://github.com/nativescript-vue/nativescript-vue-externals/issues/1

**Comment by jgirgis85** [comment] 2018-03-22 21:05
Yes, rigor I am on windows.

I read the related issue you sent me but from what I understood that this problem is not solved yet right?

**Comment by rigor789** [comment] 2018-03-22 21:06
That's correct, the problem is still there, but in the meantime you can work around it by following the comment in the linked issue. I'll close this issue since it's already tracked in the other one.

**Closed by rigor789** 2018-03-22 21:06 UTC
