### ISSUE TITLE
Error while using store with nativescript-vue typescript

### ISSUE THREAD

**Issue by azs06** [nativescript-vue/nativescript-vue#462] opened 2019-03-21 14:15 UTC
### Version
2.0.0

### Reproduction link
[https://github.com/azs06/test-ns-app](https://github.com/azs06/test-ns-app)
### Platform and OS info
Mac OS 10.14.3/Android 8.0.0/Nativescript Vue 2.0.0

### Steps to reproduce
tns preview --bundle

### What is expected?
Adding a Vuex store should just work without any issue. For example, I added this store 
```
import Vue from 'nativescript-vue'
import Vuex from 'vuex';


Vue.use(Vuex)

const debug = process.env.NODE_ENV !== 'production'

const store = new Vuex.Store({
    strict: debug
})

export default store
```
And added it to the Vue instance 
```
new Vue({
  store,		
  render: h => h('frame', [h(App)])
}).$start();
```

### What is actually happening?
Getting this error on console
```
TS2345: Argument of type '{ store: any; render(h: CreateElement): VNode; }' is not assignable to parameter of type 'ComponentOptions<NativeScriptVue<View>, DefaultData<NativeScriptVue<View>>, DefaultMethods<NativeScriptVue<View>>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>>'.
  Object literal may only specify known properties, and 'store' does not exist in type 'ComponentOptions<NativeScriptVue<View>, DefaultData<NativeScriptVue<View>>, DefaultMethods<NativeScriptVue<View>>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>>'.
```
Also vscode inidicating this error.

---
App preview works properly even with the error. Provided a GitHub link of a freshly installed project

**Comment by acidbiscuit** [comment] 2019-03-27 12:53
Type definitions that extend `ComponentOptions` and `VueConstructor` are declared inside `vuex` module. Since in reproduction project `store` is imported as `*.js` file, type definitions for `vuex` are not picked up.

Changing `store.js` to `store.ts` and corresponding import inside `main.ts` will fix the issue.

Side note: take a look [nativescript-dev-typescript](https://github.com/NativeScript/nativescript-dev-typescript) package which plugs in TypeScript into NativeScript project (uninstalling `package-lock.json`, `platforms`, `node_modules`, and `hooks` will be required, same as for most NativeScript plugins).

**Comment by azs06** [comment] 2019-03-27 13:49
@acidbiscuit Thanks, changing `store.js` to `store.ts` did solve the issue. Though there was another error, to solve that I had to install `@types/node`.

**Comment by msaelices** [comment] 2019-04-04 11:56
I've just improved the Vuex support when generating new apps using the vue-cli-template: https://github.com/nativescript-vue/vue-cli-template/pull/124 After this change, the `vue init nativescript-vue/vue-cli-template` will create a ready for use app with an empty Vuex store.

I think BTW this issue is solved so I will close it. Please re-open it if I missed something.

**Closed by msaelices** 2019-04-04 11:56 UTC
Labels: priority:normal
