### ISSUE TITLE
Make --bundle option requirement optional

### ISSUE THREAD

**Issue by Papabyte** [nativescript-vue/nativescript-vue#469] opened 2019-04-04 13:11 UTC
### What problem does this feature solve?
Since version 2.1.0 an error is thrown when you try to run without the --bundle option. In some projects, choice has been made to not use webpack cause of incompatibility with specific module (you can avoid to use webpack by exporting templates in js file instead of the usual vue files).
It would be great to have a way to discard this requirement.

### What does the proposed API look like?
Sorry, I don't have precise idea how to implement this feature.

**Comment by elena-p** [comment] 2019-05-16 09:22
@Papabyte, from the {N} 6.0 release going forward, the NativeScript CLI will support only our bundle workflow. [Here](https://www.nativescript.org/blog/the-future-of-building-nativescript-apps) is a recent blog post on the subject.

**Comment by Papabyte** [comment] 2019-05-16 10:24
@elena-p thanks for the info. 
Anyway I managed to use webpack in my project.

**Comment by rigor789** [comment] 2019-05-31 13:10
Given NativeScript is moving towards webpack only, I don't see us working on this. And as I can see, you're now able to use webpack so the issue is "resolved".

**Closed by rigor789** 2019-05-31 13:10 UTC
Labels: priority:normal
