### ISSUE TITLE
hmr: js changes not applied

### ISSUE THREAD

**Issue by dtopuzov** [nativescript-vue/nativescript-vue#470] opened 2019-04-04 14:08 UTC
### Version
2.2.1

### Platform and OS info
Android

### Steps to reproduce
```
npm i -g nativescript@latest
tns create TestApp --vue
tns run android --hmr --path TestApp
```
Then change `Blank {N}-Vue app` string inside `Home.vue` with something else.

### What is expected?
Change to be applied.

### What is actually happening?
Change is not applied.

---
Caused by this commit:
https://github.com/nativescript-vue/nativescript-vue/commit/595d2a0032de2b7b45805ef0a5266e6fd4dbe820

**Comment by msaelices** [comment] 2019-04-04 18:20
@dtopuzov Sorry but I cannot reproduce your issue:
 
![hmr-screencast-on-android](https://user-images.githubusercontent.com/136875/55578715-d40c8c80-5716-11e9-802a-876ba2ad29fe.gif)

Something more I should know for reproducing it?

**Comment by msaelices** [comment] 2019-04-04 22:38
@dtopuzov I just reproduced the error. I was using NS 5.2 and the issue happens only with NS 5.3.

Maybe @MartoYankov (NS core team) has an idea of what changed in NS 5.3 to break the HMR on Android.

**Comment by MartoYankov** [comment] 2019-04-05 10:38
@msaelices Here is the changelog for NS 5.3 - https://github.com/NativeScript/NativeScript/blob/master/CHANGELOG.md#530-2019-03-21. It seems there are a couple of improvements on hmr. Not sure if they affect Vue in any way.

**Comment by dtopuzov** [comment] 2019-04-05 10:52
@msaelices 

JS changes are synced properly with {N} 5.3 and `nativescript-vue@2.2.0`, but it fails with `nativescript-vue@2.2.1`.

**Comment by msaelices** [comment] 2019-04-05 11:46
@dtopuzov but I guess with 2.2.0 this issue is happening again: https://github.com/nativescript-vue/nativescript-vue/issues/461

I will check it now.

**Comment by dtopuzov** [comment] 2019-04-05 11:58
@msaelices Yes, it will happen. 
Now https://github.com/nativescript-vue/nativescript-vue/issues/461 is fixed, but we have this one.

**Comment by msaelices** [comment] 2019-04-05 12:19
@dtopuzov weirdly, there was a change in the {N} 5.3 which made the 2.2.0 code work well without happening the #461 issue

**Comment by msaelices** [comment] 2019-04-05 22:43
I've reverted the commit here https://github.com/nativescript-vue/nativescript-vue/commit/621e7e6318a3fe88fd72b1ec7176e7479ebcad0e as with {N}-5.3

Sorry for that round trip, I initially fixed here https://github.com/nativescript-vue/nativescript-vue/pull/444 the HMR extra navigation by hacking the internals of the NS frame as there is no public way to do it. So, the problem of this approach is that any internal change on NS could affect to the fix, and it happened here.

**Comment by mbyor** [comment] 2019-04-10 09:00
Hi @msaelices, are you planning on releasing this fix soon guys or I should rather downgrade to 2.2.0 for the time being?

**Comment by rigor789** [comment] 2019-04-10 15:41
@mbyor I'll release it in a couple of hours, when I get the chance!

**Comment by msaelices** [comment] 2019-04-12 10:41
@mbyor  The 2.2.1 is released and this version works for me. I will close the issue but re-open it if it does not work for you.

**Closed by msaelices** 2019-04-12 10:41 UTC
Labels: priority:normal
