### ISSUE TITLE
Inputs in ListView isn't working

### ISSUE THREAD

**Issue by wendt88** [nativescript-vue/nativescript-vue#405] opened 2018-12-28 09:19 UTC
### Version
2.0.2

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=n0x0DG](https://play.nativescript.org/?template=play-vue&id=n0x0DG)
### Platform and OS info
NS 5, Android 8   iOS, Windows 10

### Steps to reproduce
run Playground on Android or iOS and try also to change `<RadListView>` to `<ListView>`

### What is expected?
normal list view with a input-element to modify the data

### What is actually happening?
- RadListView:
-- iOS: after modifying a record it hangs extremely
-- Android: scrolling down it breaks the app

- ListView
-- iOS: on scroll, all switcher's starts toggling in infinity
-- Android: toggling one shitch, some others are toggling too

---
added issue to `nativescript-ui` (https://github.com/telerik/nativescript-ui-feedback/issues/966) without response, then tried a workaround with normal `<ListView>`, but it doesn't works either.
Also `<TextField>` and `<TextView>` aren't working.

It is possible, that I have to add `v-model` not to the single item? (`v-model="item.bool"` -> `v-model="items[$index].bool"`)
How can I have access to the index, because this solution doesn't works either!?

**Comment by tbozhikov** [comment] 2019-03-14 08:32
Hi @wendt88,

Some of the problems described are caused by Vue not knowing about each item's identity. To fix that you need to set `key` in the item template. See the [docs on `key`](https://vuejs.org/v2/guide/list.html#key). Example:

```xml
<ListView for="item in items">
    <v-template>
        <StackLayout :key="item.id">
            <Label :text="item.id" />
            <Label :text="item.name" />
            <Switch v-model="item.bool" />
        </StackLayout>
    </v-template>
</ListView>
```

The issues with hangs and crash in Android is fixed in [https://github.com/NativeScript/nativescript-ui-listview/releases/tag/v6.0.0](https://github.com/NativeScript/nativescript-ui-listview/releases/tag/v6.0.0). 

Let us know if you need further help.

**Comment by rigor789** [comment] 2019-03-14 11:40
What @tbozhikov suggested is correct, however in case of the ListView adding a key will defeat the purpose of the ListView, as all the recycled elements will need to be re-created as the key changes.

One way that's worth a try (I can't recall if it works as expected), is to use 
```
:checked="item.bool" @checkedChange="changeChecked(item, $event)"
```
instead of `v-model` (add `changeChecked(item, checked) { item.bool = checked }` to `methods`)

**Comment by wendt88** [comment] 2019-03-15 10:10
> instead of v-model (add changeChecked(item, checked) { item.bool = checked } to methods)

@rigor789 I tried this, but It does not works in `TextField`'s by adding `@input="item.text = $event.value"`-event, because so the cursor keeps always on first position

**Comment by wendt88** [comment] 2019-03-15 10:30
@tbozhikov By updating `nativescript-ui-listview` to v6, seems to work, at least on android, but there is a new problem:
If I use a custom vue component inside `RadListView`'s `v-template`, there is no vuex ($store) available,
also no [$i18n](https://github.com/kazupon/vue-i18n) (my translation plugin)

**Comment by tralves** [comment] 2019-03-15 11:02
@wendt88 There are lots of limitations in components inside ListView/RadListView. They have to be as "dumb" as possible. You have to process data outside the components as much as possible in the list that feeds the ListView. Even translations. I also saw several improvements when I turned my ListView items into [functional components](https://vuejs.org/v2/guide/render-function.html#Functional-Components) (which tend to be dumb too).

**Closed** 2020-05-20 16:26 UTC
Labels: priority:normal
