### ISSUE TITLE
Run preview error

### ISSUE THREAD

**Issue by anhvandev** [nativescript-vue/nativescript-vue#546] opened 2019-09-06 02:42 UTC
### **Description**
When I ran the 'tns preview' command, the software finished compiling the js code to test it, and this error occurred. I have not yet found a solution to fix it, please help me.
![ảnh](https://user-images.githubusercontent.com/49545158/64396952-9e831b00-d089-11e9-9cc5-b670e6fa154d.png)
### **Version**
2.4.0
### **Platform and OS info**
Android/ Tns Core 6.0.0 / Windows
### **Steps to reproduce**
1. install vue cli `npm install -g @vue/cli @vue/cli-init`
2. create project `vue init nativescript-vue/vue-cli-template nativescript_001`
3. install package `npm install`
4. run preview `tns preview`
5. compling, scan qr code, run and error
### **What is expected?**
App should not crash
### **What is actually happening?**
App is crashing

**Comment by rigor789** [comment] 2019-09-06 06:28
We have recently added a note to the docs about this: 
> **Note**: If you choose to install DevTools, you won't be able to use tns preview, as the Preview app doesn't support one of the plugins DevTools uses.

Either run the app locally, or disable DevTools (when creating the project say No to DevTools prompt).

Duplicate of https://github.com/nativescript-vue/nativescript-vue/issues/431

**Closed by rigor789** 2019-09-06 06:28 UTC
Labels: priority:low
