### ISSUE TITLE
Cannot overwrite margin/padding using scss 

### ISSUE THREAD

**Issue by vratojr** [nativescript-vue/nativescript-vue#332] opened 2018-09-24 17:27 UTC
### Version
1.3.1

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=DJB2mF&v=3](https://play.nativescript.org/?template=play-vue&id=DJB2mF&v=3)
### Platform and OS info
Android 6 / {N} tns_core: 3.4.1

### Steps to reproduce
* Create an app using a style.
* Create a simple form layout as displayed in the example. 
* Try to override style's default margins/paddings using css -> it works (HelloCSS in the example)
* Try to override style's default margins/paddings using scss -> it doesn't work (HelloSASS in the example)

### What is expected?
The properties should be overridden

### What is actually happening?
They are not :)

**Comment by rigor789** [comment] 2020-05-20 16:38
Closing since the issue is for 1.3.1 and the issue has likely been fixed in core!

**Closed by rigor789** 2020-05-20 16:38 UTC
Labels: priority:normal
