### ISSUE TITLE
NativeScript with Vue3 / CompositionApi

### ISSUE THREAD

**Issue by alexsserban** [nativescript-vue/nativescript-vue#583] opened 2019-11-17 16:48 UTC
Hello, We are just about to start the development process of a web & mobile app and we decided that we will continue with Vue and Nativescript as they seem the best option for us. Vue 3 is about to be released in the upcoming months, coming with the new Vue Composition Api. 

I have two questions: 

1. Will Nativescript work directly with the new version of Vue that will be realease? If not, do you have plans for making Nativescript work with Vue3? 

2. Right now there is a plugin gor Vue2 named "vue composition api" that delivers Vue3 syntax into Vue2 projects. Can we use the Vue Composition Api right now to start the development process with NativeScript? 

Thanks!
--

**Comment by kaanna** [comment] 2019-11-23 02:18
Composition API is needed for long codes. I hope we will be able to use it.

**Comment by awulkan** [comment] 2019-12-19 22:02
Any update on this? Is any work being done to have this project ready for Vue 3 when it's released? Are there any blockers?

**Comment by coffeeneed** [comment] 2020-01-01 21:36
Also need an answer to this. I hope we will be able to continue "the old way", as we'll soon release our app as of todays tech. All information regarding this question is appreciated :)

**Comment by ashbeats** [comment] 2020-01-18 07:16
Shouldn't this be considered high-priority? 3.0's composition api is finally allowing Vue to be consumed and managed in a purely functional manner away from the clunky options / oop approach.

**Comment by rigor789** [comment] 2020-01-18 13:06
We're going for a full rewrite of NativeScript-Vue for Vue 3.0

That means, we'll utilize the custom renderer API that it exposes, as well as fully support all the Vue 3.0 features including the composition API. 

I can't give an ETA, but hopefully soon after Vue 3.0 is released (not the current alphas)

**Comment by kabaluyot** [comment] 2020-04-06 07:06
As long as it is backward compatible, were happy with nativescript-vue. Please pin this issue for easy reference. Thank you for all your efforts @rigor789 , et. al

**Comment by IlyaSemenov** [comment] 2020-06-28 14:31
@vue/composition-api seems to work fine with nativescript-vue (at first glance).

**Comment by mannok** [comment] 2020-07-24 15:04
how is the progress?

**Comment by rigor789** [comment] 2020-07-24 16:31
https://github.com/rigor789/nativescript-vue-next

**Comment by shishamo** [comment] 2020-08-13 01:02
Do you have any idea about then it can be released?

**Comment by brease-colin** [comment] 2020-08-18 09:10
> @vue/composition-api seems to work fine with nativescript-vue (at first glance).

I'm experimenting with this as well and I found one thing that does not work: template references (ref). Other stuff I've tried (computed, watch, 'normal' refs, lifecycle hooks) seem to work fine, including usage of external modules (like villus for graphql).

What's not working (crashes my emulator) is the following:

```
<template>
    <grid-layout ref=componentRef />
</template>
```

```
setup() {
    const componentRef = ref<any>(null);

    return {
        componentRef,
    };
}
```

<details>
<summary>Error log</summary>

```
JS: [Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'Symbol(Symbol.toStringTag)' of undefined"
JS:
JS: found in
JS:
JS: ---> <BCalendar> at components/BCalendar.vue
JS:        <Page>
JS:          <App> at components/App.vue
JS:            <Frame>
JS:              <Root>
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to start activity ComponentInfo{nl.****.****/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: TypeError: Cannot read property 'Symbol(Symbol.toStringTag)' of undefined
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{nl.****.****/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: TypeError: Cannot read property 'Symbol(Symbol.toStringTag)' of undefined
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
System.err:     at android.app.ActivityThread.access$800(ActivityThread.java:151)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)      
System.err:     at android.os.Looper.loop(Looper.java:135)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5254)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
System.err: Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: TypeError: Cannot read property 'Symbol(Symbol.toStringTag)' of undefined
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)       
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1160)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1138)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1134)
System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:19)
System.err:     at android.app.Activity.performCreate(Activity.java:5990)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
System.err:     ... 10 more
ActivityManager: Process nl.****.**** (pid 24182) has died
```

</details>

I understand if this is something for nativescript-vue-next though, but maybe someone knows of a nice workaround.

**Comment by IlyaSemenov** [comment] 2020-08-19 07:36
@brease-colin I've stumbled across the same problem, my workaround was:

```vue
<script lang="ts">
export default defineComponent({
       setup(_, { refs }) {
               let drawer: RadSideDrawer

               // workaround for refs
               // for some reason string refs didn't work per
               // https://github.com/vuejs/composition-api#template-refs
               const $refs = refs as {
                       drawer: Vue<RadSideDrawer>
               }

               onMounted(() => {
                       drawer = $refs.drawer.nativeView
               })

               // ...
       },
})
</script>

<template>
       <RadSideDrawer ref="drawer">
               <slot />
       </RadSideDrawer>
</template>
```

(I then ditched RadSideDrawer for nativescript-vue-multi-drawer which doesn't need a ref to operate).

**Comment by brease-colin** [comment] 2020-08-19 08:36
@IlyaSemenov  Thanks for sharing, that should work nicely indeed! 👍

**Comment by lovetingyuan** [comment] 2020-09-05 06:12
`Custom Renderer API ` provided by Vue 3 is most important feature for NativeScript.

**Comment by luisfer7192** [comment] 2020-09-24 01:07
Hi @rigor789,
Do you have any idea about then it can be released?

**Comment by Pckool** [comment] 2020-09-29 00:01
It seems like there is a [public npm package of this new version](https://www.npmjs.com/package/nativescript-vue/v/3.0.0-dev.4)

**Comment by rigor789** [comment] 2020-09-29 07:36
I showed a demo and it's published as an early preview, undocumented yet: https://www.youtube.com/watch?v=QuEEF-QvfmU

**Comment by Linkontoask** [comment] 2020-11-05 03:59
Great, waiting for release

**Comment by HakobiDev** [comment] 2020-11-07 20:14
+1 Hoping to bring it to life it seems the author quoting 
"(off-topic) progress has been slow, as I frankly didn't have time/motivation to do it.".

Still missing the new features of Vue 3(Composition API) for big codebase app.
No specific ETA for NS-V3, sad but true. 

I know it is hard to rewrite the whole NS-V2 to V3. Hopefully more contributors to all NS-V2 users

**Comment by deindesignpl** [comment] 2020-12-16 20:45
+1 Hoping to bring it to life as well

**Comment by andresilva-cc** [comment] 2021-04-18 21:57
Any news on this?

**Comment by uptownhr** [comment] 2021-04-27 18:05
> We're going for a full rewrite of NativeScript-Vue for Vue 3.0
> 
> That means, we'll utilize the custom renderer API that it exposes, as well as fully support all the Vue 3.0 features including the composition API.
> 
> I can't give an ETA, but hopefully soon after Vue 3.0 is released (not the current alphas)

I see 411 commits in the https://github.com/rigor789/nativescript-vue-next repo. However seeing that commits have stopped in December of 2020. Has development stopped?

**Comment by baermathias** [comment] 2021-05-19 15:56
@rigor789 could you tell us a little bit about the state of nativescript-vue 3 ?

**Comment by foxgreek** [comment] 2021-07-14 08:33
@rigor789 are there any news about nativescript-vue 3?

**Comment by mannok** [comment] 2021-07-20 08:49
@rigor789 are you giving up vue 3 on nativescript?

**Comment by rigor789** [comment] 2021-07-20 19:46
@mannok not at all, just haven't really had any free time lately to work on it.

**Comment by anburocky3** [comment] 2021-09-16 19:44
Is Nativescript With Vue3 released?, its been a year.

**Comment by MattCCC** [comment] 2021-09-25 13:33
Work is ongoing on another repo: https://github.com/rigor789/nativescript-vue-next.

**Comment by mannok** [comment] 2022-01-11 14:40
@rigor789 hi bro, is there a estimate time to continue this repo? I would like to start my new project with NS Vue 3

**Comment by andresilva-cc** [comment] 2022-01-12 11:59
@mannok I wouldn't count on that, looks like the development has stopped a while ago. I already gave up on NativeScript Vue and also NativeScript itself, moving to Flutter.

**Comment by mannok** [comment] 2022-01-12 16:18
@rigor789 so sad to hear that :(

**Comment by Khaled-Aller** [comment] 2022-03-21 18:04
Is there any news on this one?

**Comment by cristiantorres91** [comment] 2022-05-20 14:20
something new? 
still can't use vue 3 with nativescript?

**Comment by erik777** [comment] 2022-11-06 16:44
@rigor789 if you are very busy on other projects what do you think about hosting a live or uploading a video on an overview of the project to introduce new contributors to it?  

- process for handling updates from upstream (nativescript, navitescript-vue [v2])
- code layout and how to change this or that
- current outstanding issues.  definition of 'ready'
- testing process
- anything else to help onramp contributors
- Q&A

**Comment by Fabiyo-90** [comment] 2022-11-09 10:35
@erik777 , comme to discord, @rigor789 is more reactive 

https://discord.com/channels/603595811204366337/615931901756309514/1039844232992669706

**Comment by rigor789** [comment] 2022-11-09 12:24
@erik777 @Fabiyo-90 It's a great idea, not sure I have the time right now to do a full walk-through, however I am usually very active on Discord, and happy to answer any questions that come up.

https://nativescript.org/discord

A short version is:
 - periodically update everything to latest, and see if it compiles. If not, adjust build setup in case the tooling changed (rollup).
 - run the sample app, and try a few different samples by adjusting the entry file import (it should auto restart the app on change, so quite quick to go through a few).
 - there are some unit tests that mostly cover the renderer/dom implementation, these should generally pass, so if anything doesn't, that would indicate a problem usually - though probably rare.
 - apart from that, drop the new version into a client app and test it just to make sure things still work.
 - The process is not ideal, but given that we don't really mess with NativeScript core too much, we don't really need to cover that part in tests, the most important bits are the renderer/dom. Same goes for Vue, it's already tested on the Vue side, so we don't need to test it too much, we can assume it's working as intended.

Most of the source is handled in: https://github.com/nativescript-vue/nativescript-vue/tree/main/platform/nativescript

The dom stuff is here: https://github.com/nativescript-vue/nativescript-vue/tree/main/platform/nativescript/renderer

**Comment by rigor789** [comment] 2022-12-05 18:26
It's now available in **beta**!

https://twitter.com/igor_randj/status/1599830172143788032

**Closed by rigor789** 2022-12-05 18:26 UTC
Labels: priority:low, V2

**Comment by mannok** [comment] 2022-12-06 01:42
@rigor789 I've been waited for soooooooooo long....   FINALLY.........

**Comment by SendDerek** [comment] 2023-05-19 15:10
I'm glad to see some progress with Vue 3.  Thank you! 🙏  

It's been about 6 months since the beta was announced.  What are the plans for a full release?  Looking at Vue2 LTS, we have until the end of this year.

[About Vue2 LTS](https://v2.vuejs.org/lts/):
_Vue 2 will reach End of Life (EOL) on December 31st, 2023. After that date, Vue 2 will continue to be available in all existing distribution channels (CDNs and package managers), but will no longer receive updates, including security and browser compatibility fixes._

**Comment by BroJenuel** [comment] 2024-01-10 15:06
any update on this? os this added to native script? vue3 support?
