### ISSUE TITLE
Cannot use vue-i18n in components with vue-router

### ISSUE THREAD

**Issue by hoatructhanhlam** [nativescript-vue/nativescript-vue#135] opened 2018-03-12 17:53 UTC
it work ok in App.vue file with render: h => h(App) in entry file main.js.

but i get a error message 
```JS: [Vue warn]: Error in render: "TypeError: Cannot read property '_t' of undefined"```
when use $t('key') in components.

**Comment by guyaumetremblay** [comment] 2018-03-12 18:09
@rigor789 Seems te same problem that I faced in #70 (but I didn't get the time to investigate / reproduce it since you closed it )

**Comment by rigor789** [comment] 2018-03-12 18:18
@hoatructhanhlam can you try it without `vue-router` that could be the culprit until it's fixed according to #119 

@guyaumetremblay you are right, this is probably the same issue and most likely caused by the current router implementation.

**Comment by Informateur** [comment] 2018-03-13 07:47
I'm using vuex-i18n. It is more functional for dynamic translation. So far, there have been no problems with him.

**Comment by hoatructhanhlam** [comment] 2018-03-13 13:44
> What the version of Nativescript-Vue being used by you?
I get problem with NSV latest (1.3.1)

**Comment by hoatructhanhlam** [comment] 2018-03-15 01:27
Thank @Informateur I can resolve this problem with vuex-i18n. I'll close this issue

**Closed** 2018-03-15 01:27 UTC
