### ISSUE TITLE
Keep-Alive feature please

### ISSUE THREAD

**Issue by ukik** [nativescript-vue/nativescript-vue#643] opened 2020-05-14 20:49 UTC
I use Nativescript-Vue + Nativescript old version, it supports Keep-Alive, but not is not supported.

Keep-Alive is important feature in Vue eccosystem to avoid redendering UI multiple times. For example I use Form, so I just need to render it once, and keep it alive. So when I back to that page, I just change its data using keep-alive components, it is fasten user experience, and of course when user fill data but incidentally pressed back button, user can back to the page to continue his input.

Any idea to support Keep-Alive? or make it feature disappear in Nativescript-Vue.....

Please bring back Keep-Alive like before.

**Comment by rigor789** [comment] 2020-05-19 18:11
duplicate of #642

**Closed by rigor789** 2020-05-19 18:11 UTC
Labels: priority:low
